---
# roles/template/tasks/main.yml
- name: Ensure the ~/.local directory exists
  file:
    path: $HOME/.local
    state: directory
  tags:
    - bashrc

- name: Add the ldea lines to .bashrc
  lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
  loop:
    - PROMPT_COMMAND='stty sane'
    - export PATH=$PATH:$HOME/.local/bin
    - '[ -f $HOME/.ssh/config ] && complete -o default -o nospace -W "$(grep "^Host" $HOME/.ssh/config | cut -d " " -f2)" scp sftp ssh'
    - '[ -f /usr/share/doc/fzf/examples/key-bindings.bash ] && source /usr/share/doc/fzf/examples/key-bindings.bash'
    - '[ -f /usr/share/doc/fzf/examples/completion.bash ] && source /usr/share/doc/fzf/examples/completion.bash'
    - 'git config --global alias.graph "log --graph --abbrev-commit --decorate --oneline --all"'
    - "alias activate='source ./venv/bin/activate'"
  tags:
    - bashrc


